// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZuwTUZaBOYKthpjfdkyYUvrBIMFW-Dgs',
    appId: '1:205005601964:web:11ffb192b7607fbbc0f309',
    messagingSenderId: '205005601964',
    projectId: 'task3-3a62b',
    authDomain: 'task3-3a62b.firebaseapp.com',
    storageBucket: 'task3-3a62b.appspot.com',
    measurementId: 'G-L96YC3BMWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4zf9zLCvmperw9uY5F54yeqlNvdtx_AA',
    appId: '1:205005601964:android:96cb0501b011f311c0f309',
    messagingSenderId: '205005601964',
    projectId: 'task3-3a62b',
    storageBucket: 'task3-3a62b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3RI6Z8Cwb6xyovhVL6QFc0Oyspw9OH6M',
    appId: '1:205005601964:ios:6f9a1cf9f2b68c51c0f309',
    messagingSenderId: '205005601964',
    projectId: 'task3-3a62b',
    storageBucket: 'task3-3a62b.appspot.com',
    iosClientId: '205005601964-phflelf6s9qqr7l8s99jkdis70pari7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3RI6Z8Cwb6xyovhVL6QFc0Oyspw9OH6M',
    appId: '1:205005601964:ios:6f9a1cf9f2b68c51c0f309',
    messagingSenderId: '205005601964',
    projectId: 'task3-3a62b',
    storageBucket: 'task3-3a62b.appspot.com',
    iosClientId: '205005601964-phflelf6s9qqr7l8s99jkdis70pari7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZuwTUZaBOYKthpjfdkyYUvrBIMFW-Dgs',
    appId: '1:205005601964:web:8ea860bb2482b803c0f309',
    messagingSenderId: '205005601964',
    projectId: 'task3-3a62b',
    authDomain: 'task3-3a62b.firebaseapp.com',
    storageBucket: 'task3-3a62b.appspot.com',
    measurementId: 'G-QYJFM2XJK9',
  );

}